/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoZoo.challenge;

import algoZoo.game.LevelButton;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Thiss class is for organizing the LevelButtons for Challenge Mode
 * @author Ayberk, Doğa, Esra, Alp
 * @version 1.0
 */
public class ChallengeModeLevelsGUI extends javax.swing.JPanel {

   // properties
   ArrayList<LevelButton> buttons;
   ArrayList<JLabel>  stars;

   // constructor
   public ChallengeModeLevelsGUI() {
       //initialize all components
      initComponents();
      buttons = new ArrayList<LevelButton>();
      stars = new ArrayList<>();
      
      //add necessary components to ArrayLists
      addButtons();    
      addStars();
   }
   
   //methods
   /**
    * Adds all the efficiency jLabels to ArrayList
    */
   public void addStars() {
      stars.add(stars1);
      stars.add(stars2);
      stars.add(stars3);
      stars.add(stars4);
      stars.add(stars5);
      stars.add(stars6);
      stars.add(stars7);
      stars.add(stars8);
      stars.add(stars9);
      stars.add(stars10);     
   }
   
   /**
    * Adds all the LevelButtons to ArrayList
    */
   public void addButtons() {
      buttons.add(levelOne);
      buttons.add(levelTwo);
      buttons.add(levelThree);
      buttons.add(levelFour);
      buttons.add(levelFive);
      buttons.add(levelSix);
      buttons.add(levelSeven);
      buttons.add(levelEight);
      buttons.add(levelNine);
      buttons.add(levelTen);
      //set the unplayed levels' buttons disabled
      for ( int i = 1; i < buttons.size(); i++) {
         buttons.get(i).setEnabled(false);
      }
   }

   /**
    * Returns the efficiency label of the given levelNo
    * @param levelNo
    * @return stars.get(levelNo - 1)
    */
   public JLabel getJLabel(int levelNo)  {
      return stars.get(levelNo - 1);
   }
   
   /**
    * Returns the LevelButton of the given levelNo
    * @param levelNo
    * @return buttons.get(levelNo - 1)
    */
   public LevelButton getJButton(int levelNo) {
      return buttons.get(levelNo - 1);
   }

   /**
    * Sets the icon of the LevelButton with given ImageIcon
    * @param levelButton
    * @param icon 
    */
   public void setJButtonIcon(LevelButton levelButton, ImageIcon icon) {
      levelButton.setIcon(icon);
   }
   
   /**
    * Sets the icon of efficiency labels according to the efficiency of played level
    * @param stars
    * @param efficiency 
    */
   public void setEfficiencyStars(JLabel stars, int efficiency) {
       if(efficiency == 3)
           stars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Stars/Three_Stars.png")));
       else if(efficiency == 2) 
           stars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Stars/Two_Stars.png")));
       else if(efficiency == 1)
           stars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Stars/One_Star.png")));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelOne = new algoZoo.game.LevelButton(1);
        levelTwo = new algoZoo.game.LevelButton(2);
        levelThree = new algoZoo.game.LevelButton(3);
        levelFour = new algoZoo.game.LevelButton(4);
        levelFive = new algoZoo.game.LevelButton(5);
        levelSix = new algoZoo.game.LevelButton(6);
        levelSeven = new algoZoo.game.LevelButton(7);
        levelEight = new algoZoo.game.LevelButton(8);
        levelNine = new algoZoo.game.LevelButton(9);
        levelTen = new algoZoo.game.LevelButton(10);
        stars1 = new javax.swing.JLabel();
        stars2 = new javax.swing.JLabel();
        stars3 = new javax.swing.JLabel();
        stars4 = new javax.swing.JLabel();
        stars5 = new javax.swing.JLabel();
        stars6 = new javax.swing.JLabel();
        stars7 = new javax.swing.JLabel();
        stars8 = new javax.swing.JLabel();
        stars9 = new javax.swing.JLabel();
        stars10 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(null);

        levelOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/1.png"))); // NOI18N
        levelOne.setBorder(null);
        levelOne.setContentAreaFilled(false);
        levelOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(levelOne);
        levelOne.setBounds(255, 350, 95, 95);

        levelTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelTwo.setBorder(null);
        levelTwo.setContentAreaFilled(false);
        levelTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelTwo);
        levelTwo.setBounds(455, 350, 95, 95);

        levelThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelThree.setBorder(null);
        levelThree.setContentAreaFilled(false);
        levelThree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelThree);
        levelThree.setBounds(655, 350, 95, 95);

        levelFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelFour.setBorder(null);
        levelFour.setContentAreaFilled(false);
        levelFour.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelFour);
        levelFour.setBounds(855, 350, 95, 95);

        levelFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelFive.setBorder(null);
        levelFive.setContentAreaFilled(false);
        levelFive.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelFive);
        levelFive.setBounds(1055, 350, 95, 95);

        levelSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelSix.setBorder(null);
        levelSix.setContentAreaFilled(false);
        levelSix.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelSix);
        levelSix.setBounds(255, 550, 95, 95);

        levelSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelSeven.setBorder(null);
        levelSeven.setContentAreaFilled(false);
        levelSeven.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelSeven);
        levelSeven.setBounds(455, 550, 95, 95);

        levelEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelEight.setBorder(null);
        levelEight.setContentAreaFilled(false);
        levelEight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelEight);
        levelEight.setBounds(655, 550, 95, 95);

        levelNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelNine.setBorder(null);
        levelNine.setContentAreaFilled(false);
        levelNine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelNine);
        levelNine.setBounds(855, 550, 95, 95);

        levelTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Challenge Mode/Lock.png"))); // NOI18N
        levelTen.setBorder(null);
        levelTen.setContentAreaFilled(false);
        levelTen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(levelTen);
        levelTen.setBounds(1055, 550, 95, 95);

        stars1.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars1);
        stars1.setBounds(228, 300, 150, 40);

        stars2.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars2);
        stars2.setBounds(428, 300, 150, 40);

        stars3.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars3);
        stars3.setBounds(628, 300, 150, 40);

        stars4.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars4);
        stars4.setBounds(828, 300, 150, 40);

        stars5.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars5);
        stars5.setBounds(1028, 300, 150, 40);

        stars6.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars6);
        stars6.setBounds(228, 500, 150, 40);

        stars7.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars7);
        stars7.setBounds(428, 500, 150, 40);

        stars8.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars8);
        stars8.setBounds(628, 500, 150, 40);

        stars9.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars9);
        stars9.setBounds(828, 500, 150, 40);

        stars10.setPreferredSize(new java.awt.Dimension(48, 40));
        add(stars10);
        stars10.setBounds(1028, 500, 150, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/Challenge_Mode_Levels_Background.png"))); // NOI18N
        add(background);
        background.setBounds(0, 0, 1400, 800);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private algoZoo.game.LevelButton levelEight;
    private algoZoo.game.LevelButton levelFive;
    private algoZoo.game.LevelButton levelFour;
    private algoZoo.game.LevelButton levelNine;
    private algoZoo.game.LevelButton levelOne;
    private algoZoo.game.LevelButton levelSeven;
    private algoZoo.game.LevelButton levelSix;
    private algoZoo.game.LevelButton levelTen;
    private algoZoo.game.LevelButton levelThree;
    private algoZoo.game.LevelButton levelTwo;
    private javax.swing.JLabel stars1;
    private javax.swing.JLabel stars10;
    private javax.swing.JLabel stars2;
    private javax.swing.JLabel stars3;
    private javax.swing.JLabel stars4;
    private javax.swing.JLabel stars5;
    private javax.swing.JLabel stars6;
    private javax.swing.JLabel stars7;
    private javax.swing.JLabel stars8;
    private javax.swing.JLabel stars9;
    // End of variables declaration//GEN-END:variables
}
