/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoZoo.learn;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ayberk
 */
public class LearnModeLevelsGUI extends javax.swing.JPanel {
   
   /**
    * Creates new form LearnModeLevelsGUI
    */
   public LearnModeLevelsGUI() {
      initComponents();
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jButton7 = new javax.swing.JButton();
      jButton8 = new javax.swing.JButton();
      jButton9 = new javax.swing.JButton();
      jButton10 = new javax.swing.JButton();
      background = new javax.swing.JLabel();

      setLayout(null);

      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/1.png"))); // NOI18N
      jButton1.setBorder(null);
      jButton1.setContentAreaFilled(false);
      jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      add(jButton1);
      jButton1.setBounds(255, 350, 95, 95);

      jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton2.setBorder(null);
      jButton2.setContentAreaFilled(false);
      jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton2);
      jButton2.setBounds(455, 350, 95, 95);

      jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton3.setBorder(null);
      jButton3.setContentAreaFilled(false);
      jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton3);
      jButton3.setBounds(655, 350, 95, 95);

      jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton4.setBorder(null);
      jButton4.setContentAreaFilled(false);
      jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton4);
      jButton4.setBounds(855, 350, 95, 95);

      jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton5.setBorder(null);
      jButton5.setContentAreaFilled(false);
      jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton5);
      jButton5.setBounds(1055, 350, 95, 95);

      jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton6.setBorder(null);
      jButton6.setContentAreaFilled(false);
      jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton6);
      jButton6.setBounds(255, 550, 95, 95);

      jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton7.setBorder(null);
      jButton7.setContentAreaFilled(false);
      jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton7);
      jButton7.setBounds(455, 550, 95, 95);

      jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton8.setBorder(null);
      jButton8.setContentAreaFilled(false);
      jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton8);
      jButton8.setBounds(655, 550, 95, 95);

      jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton9.setBorder(null);
      jButton9.setContentAreaFilled(false);
      jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton9);
      jButton9.setBounds(855, 550, 95, 95);

      jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Levels/Learn Mode/Lock.png"))); // NOI18N
      jButton10.setBorder(null);
      jButton10.setContentAreaFilled(false);
      jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      add(jButton10);
      jButton10.setBounds(1055, 550, 95, 95);

      background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/Learn_Mode_Levels_Background.png"))); // NOI18N
      add(background);
      background.setBounds(0, 0, 1400, 800);
   }// </editor-fold>//GEN-END:initComponents
   
   
   public JButton getjButton1() {
      return jButton1;
   }

   public JButton getjButton10() {
      return jButton10;
   }

   public JButton getjButton2() {
      return jButton2;
   }

   public JButton getjButton3() {
      return jButton3;
   }

   public JButton getjButton4() {
      return jButton4;
   }

   public JButton getjButton5() {
      return jButton5;
   }

   public JButton getjButton6() {
      return jButton6;
   }

   public JButton getjButton7() {
      return jButton7;
   }

   public JButton getjButton8() {
      return jButton8;
   }

   public JButton getjButton9() {
      return jButton9;
   }
   
   

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel background;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton10;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JButton jButton8;
   private javax.swing.JButton jButton9;
   // End of variables declaration//GEN-END:variables
}
