/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoZoo.test;

import algoZoo.game.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Kerem, Arda
 */
public class TestModeGUI extends javax.swing.JPanel {

    //properties

    TestSelectionButtonsController options;
    MapView map;
    TestModeModel tmm;
    CodeView codeView;
    /**
     * Creates new form TestModeLevelsGUI
     */
    public TestModeGUI() {
        initMyComponents();
        initComponents();
        this.map = map;
    }
    private void initMyComponents(){
        ArrayList<Character> list1 = new ArrayList<Character>();
        list1.add('s');
        list1.add('s');
        list1.add('s');
        list1.add('d');
        list1.add('w');
        list1.add('s');
        list1.add('d');
        list1.add('d');
        list1.add('s');
        list1.add('s');
        
        ArrayList<Character> list2 = new ArrayList<Character>();
        list2.add('d');
        list2.add('d');
        list2.add('s');
        list2.add('d');
        list2.add('w');
        list2.add('s');
        list2.add('d');
        list2.add('d');
        list2.add('a');
        list2.add('d');
        
        ArrayList<Character> list3 = new ArrayList<Character>();
        list3.add('s');
        list3.add('d');
        list3.add('s');
        list3.add('d');
        list3.add('w');
        list3.add('a');
        list3.add('s');
        list3.add('d');
        list3.add('w');
        list3.add('d');
        
        tmm = new TestModeModel(new Animal("Bee", new ImageIcon(getClass().getResource("/algoZoo/Icons/Animals/bee.png"))),8, 12, 72, 76);
        map = new MapView(tmm);
        options = new TestSelectionButtonsController(tmm, list1, list2, list3);
        add(map);
        map.setBounds(50, 50, 640, 640);
        add(options);
        options.setBounds(700, 0, 700, 800);
        tmm.addView(map);
        
        if(tmm.HasWon()){
            System.out.println("won");
        }
    }
    public void initNewGame() {
        tmm.initNewGame();        
        
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        codeView1 = new algoZoo.game.CodeView();

        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/In_Game_Background.png"))); // NOI18N
        add(background);
        background.setBounds(0, 0, 1400, 800);
        add(codeView1);
        codeView1.setBounds(740, 60, 350, 630);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel codeView1;
    // End of variables declaration//GEN-END:variables
}
