/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoZoo.game;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;

/**
 *
 * @author Ayberk, Görkem
 */
public class CodeView extends javax.swing.JPanel implements IAlgoZooView {
   // properties
   ArrayList<JLabel> jlabels;
   // constructor
   public CodeView() {
      initComponents();
      jlabels = new ArrayList<>();
   }
   
   // methods
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setLayout(null);
   }// </editor-fold>//GEN-END:initComponents

   @Override
   public void updateView(AlgoZooModel azm) {
      Iterator itr = azm.getMovementPattern().iterator();

      while (itr.hasNext()) {
         if ((char) itr.next() == 'w') {
            jlabels.add(new JLabel());
            //jlabels.get(jlabels.size() - 1).setIcon(icon);
            //jlabels.get(jlabels.size() - 1).setBounds(x,y,100,50);
         } 
         else if ((char) itr.next() == 'a') {
            jlabels.add(new JLabel());
            //jlabels.get(jlabels.size() - 1).setIcon(icon);
            //jlabels.get(jlabels.size() - 1).setBounds(x,y,100,50);
         } 
         else if ((char) itr.next() == 's') {
            jlabels.add(new JLabel());
            //jlabels.get(jlabels.size() - 1).setIcon(icon);
            //jlabels.get(jlabels.size() - 1).setBounds(x,y,100,50);
         } 
         else if ((char) itr.next() == 'd') {
            jlabels.add(new JLabel());
            //jlabels.get(jlabels.size() - 1).setIcon(icon);
            //jlabels.get(jlabels.size() - 1).setBounds(x,y,100,50);
         }
      }
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
