package algoZoo.game;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 * This class represents the screen when info button is pressed.
 * @author Ayberk, Kerem, Arda
 */
public class InfoScreen extends javax.swing.JPanel {

    /**
     * Creates new form InfoScreen
     */
    public InfoScreen() {
      initComponents();
      infoScreen2.setVisible(false);
    }
    
    // methods
    /**
    * Method to play sound when buttons clicked.
    * @param soundName 
    */
   private void playSound(String filePath) 
   {     
        try 
        {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(filePath) );
            Clip clip = AudioSystem.getClip( );
            clip.open(audioInputStream);
            clip.start( );
        }
        catch(Exception ex)
        {
            System.out.println("Error with playing sound.");
            ex.printStackTrace( );
        }
   }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      previous = new javax.swing.JButton();
      next = new javax.swing.JButton();
      infoScreen1 = new javax.swing.JLabel();
      infoScreen2 = new javax.swing.JLabel();
      background = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1400, 800));
      setMinimumSize(new java.awt.Dimension(1207, 661));
      setPreferredSize(new java.awt.Dimension(1207, 661));
      setLayout(null);

      previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Previous_Change_Button.png"))); // NOI18N
      previous.setBorder(null);
      previous.setContentAreaFilled(false);
      previous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      previous.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            previousMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            previousMouseExited(evt);
         }
      });
      previous.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            previousActionPerformed(evt);
         }
      });
      add(previous);
      previous.setBounds(1220, 660, 36, 60);

      next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Next_Change_Button.png"))); // NOI18N
      next.setBorder(null);
      next.setContentAreaFilled(false);
      next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      next.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            nextMouseEntered(evt);
         }
         public void mouseExited(java.awt.event.MouseEvent evt) {
            nextMouseExited(evt);
         }
      });
      next.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            nextActionPerformed(evt);
         }
      });
      add(next);
      next.setBounds(1260, 660, 36, 60);

      infoScreen1.setForeground(new java.awt.Color(255, 255, 255));
      infoScreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/InfoScreen_1.png"))); // NOI18N
      add(infoScreen1);
      infoScreen1.setBounds(100, 75, 1207, 661);

      infoScreen2.setForeground(new java.awt.Color(255, 255, 255));
      infoScreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/InfoScreen_2.png"))); // NOI18N
      add(infoScreen2);
      infoScreen2.setBounds(100, 75, 1207, 661);

      background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/Mode_Screen_Background.png"))); // NOI18N
      add(background);
      background.setBounds(0, 0, 1400, 800);
   }// </editor-fold>//GEN-END:initComponents

   private void previousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseEntered
      previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Previous_Change_Button_Clicked.png")));
   }//GEN-LAST:event_previousMouseEntered

   private void previousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseExited
      previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Previous_Change_Button.png")));
   }//GEN-LAST:event_previousMouseExited

   private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
      if (infoScreen1.isVisible()) {
         infoScreen1.setVisible(false);
         infoScreen2.setVisible(true);
      }
      else {
         infoScreen1.setVisible(true);
         infoScreen2.setVisible(false);
      }
      playSound( "src/algoZoo/Sounds/Info_Button.wav" ); 
   }//GEN-LAST:event_previousActionPerformed

   private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
      next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Next_Change_Button_Clicked.png")));
   }//GEN-LAST:event_nextMouseEntered

   private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
      next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Icons/Buttons/Next_Change_Button.png")));
   }//GEN-LAST:event_nextMouseExited

   private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
      if (infoScreen1.isVisible()) {
         infoScreen1.setVisible(false);
         infoScreen2.setVisible(true);
      }
      else {
         infoScreen1.setVisible(true);
         infoScreen2.setVisible(false);
      }
      playSound( "src/algoZoo/Sounds/Info_Button.wav" ); 
   }//GEN-LAST:event_nextActionPerformed
    
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel background;
   private javax.swing.JLabel infoScreen1;
   private javax.swing.JLabel infoScreen2;
   private javax.swing.JButton next;
   private javax.swing.JButton previous;
   // End of variables declaration//GEN-END:variables
}
