/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoZoo.game;

import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 * This class represents the screen when info button is pressed.
 * @author Ayberk, Kerem, Arda
 */
public class InfoScreen extends javax.swing.JPanel {

    //JScrollPane jScrollPane1;
    /**
     * Creates new form InfoScreen
     */
    public InfoScreen() {
      initComponents();
      //initMyComponents();
      //jScrollPane1.getViewport().setOpaque(true);
      //jScrollPane1.setOpaque(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();

      setMaximumSize(new java.awt.Dimension(1400, 800));
      setMinimumSize(new java.awt.Dimension(1207, 661));
      setPreferredSize(new java.awt.Dimension(1207, 661));
      setLayout(null);

      jLabel1.setForeground(new java.awt.Color(255, 255, 255));
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/Info_Screen.png"))); // NOI18N
      add(jLabel1);
      jLabel1.setBounds(100, 75, 1207, 661);

      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoZoo/Backgrounds/Mode_Screen_Background.png"))); // NOI18N
      add(jLabel2);
      jLabel2.setBounds(0, 0, 1400, 800);
   }// </editor-fold>//GEN-END:initComponents
    /*
    private void initMyComponents(){
	JTextArea textArea = new JTextArea();
        textArea.setEditable(false);
        
        jScrollPane1 = new JScrollPane(textArea);
        try {
            textArea.read(new InputStreamReader(
                    getClass().getResourceAsStream("HowToPlay.txt")),
                null);
        } catch (IOException e) {
            e.printStackTrace();
        }
        jScrollPane1.setVisible(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(755, 610));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(755, 610));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(755, 610));
        jLabel1.add(jScrollPane1);
        jScrollPane1.setBounds(287, 91, 755, 610);
    }*/

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   // End of variables declaration//GEN-END:variables
}
